data_path: /root/code/Multi-labelClothingDetection/dataset/voc.yaml
conf_file: configs/yolov6n.py
img_size: 640
rect: false
batch_size: 220
epochs: 300
workers: 8
device: 0,1
eval_interval: 20
eval_final_only: false
heavy_eval_range: 50
check_images: true
check_labels: true
output_dir: ./runs/train
name: /root/code/Multi-labelClothingDetection/runs/v6n_coco_multiGPU
dist_url: env://
gpu_count: 0
local_rank: 0
resume: false
write_trainbatch_tb: true
stop_aug_last_n_epoch: 15
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
fuse_ab: true
bs_per_gpu: 32
specific_shape: false
height: null
width: null
rank: 0
world_size: 2
save_dir: /root/code/Multi-labelClothingDetection/runs/v6n_coco_multiGPU
